/**
 * @file conversions.hpp
 * @brief IEC 61131-3 standard type conversion functions
 * @author Salvatore Bamundo
 * @date July 2026
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: Copyright (c) 2026 undoRT
 *
 * This header provides the runtime implementation of IEC 61131-3
 * standard conversion functions (Table 3 of the standard) used by
 * code generated by the st2cpp compiler.
 *
 * Rounding convention:
 *   Conversions from floating point to integer types follow IEC
 *   61131-3 semantics: round to nearest, ties away from zero.
 *   This differs from a plain C++ static_cast, which truncates
 *   toward zero. Use TRUNC_* variants when truncation is required.
 *
 * Date/time convention:
 *   DATE and DATE_AND_TIME are stored as seconds since 1970-01-01 UTC.
 *   TIME_OF_DAY and TIME are stored as milliseconds. All calendar
 *   decomposition is performed in UTC (gmtime), never local time,
 *   to keep conversions deterministic regardless of host timezone.
 */

#pragma once

#include <cmath>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <string>
#include <stdexcept>
#include <codecvt>
#include <locale>

#include "types.hpp"

namespace undoCore {

// Internal rounding helper (IEC: round to nearest, ties away from zero)

namespace detail {

inline Double iecRound(Double value)
{
    return std::round(value); // round-half-away-from-zero, matches IEC semantics
}

} // namespace detail

// Integer <-> Integer conversions

inline DINT INT_TO_DINT(INT v)   { return static_cast<DINT>(v); }
inline INT  DINT_TO_INT(DINT v)  { return static_cast<INT>(v); }   // narrowing, wraps
inline LINT DINT_TO_LINT(DINT v) { return static_cast<LINT>(v); }
inline DINT LINT_TO_DINT(LINT v) { return static_cast<DINT>(v); }  // narrowing, wraps

inline UINT  INT_TO_UINT(INT v)   { return static_cast<UINT>(v); }
inline INT   UINT_TO_INT(UINT v)  { return static_cast<INT>(v); }
inline UDINT DINT_TO_UDINT(DINT v){ return static_cast<UDINT>(v); }
inline DINT  UDINT_TO_DINT(UDINT v){ return static_cast<DINT>(v); }

inline SINT  INT_TO_SINT(INT v)   { return static_cast<SINT>(v); } // narrowing, wraps
inline INT   SINT_TO_INT(SINT v)  { return static_cast<INT>(v); }

// SINT promotion/demotion chain (widens: exact, narrows: wraps)

inline DINT SINT_TO_DINT(SINT v) { return static_cast<DINT>(v); }
inline LINT SINT_TO_LINT(SINT v) { return static_cast<LINT>(v); }
inline SINT DINT_TO_SINT(DINT v) { return static_cast<SINT>(v); } // narrowing, wraps
inline SINT LINT_TO_SINT(LINT v) { return static_cast<SINT>(v); } // narrowing, wraps

// Integer -> Floating point (exact, no rounding needed)

inline REAL  INT_TO_REAL(INT v)   { return static_cast<REAL>(v); }
inline REAL  DINT_TO_REAL(DINT v) { return static_cast<REAL>(v); }
inline REAL  LINT_TO_REAL(LINT v) { return static_cast<REAL>(v); }
inline REAL  SINT_TO_REAL(SINT v) { return static_cast<REAL>(v); }

inline LREAL INT_TO_LREAL(INT v)   { return static_cast<LREAL>(v); }
inline LREAL DINT_TO_LREAL(DINT v) { return static_cast<LREAL>(v); }
inline LREAL LINT_TO_LREAL(LINT v) { return static_cast<LREAL>(v); }
inline LREAL SINT_TO_LREAL(SINT v) { return static_cast<LREAL>(v); }

// Floating point -> Integer (IEC rounding: nearest, ties away from zero)

inline INT  REAL_TO_INT(REAL v)   { return static_cast<INT>(detail::iecRound(v)); }
inline DINT REAL_TO_DINT(REAL v)  { return static_cast<DINT>(detail::iecRound(v)); }
inline LINT REAL_TO_LINT(REAL v)  { return static_cast<LINT>(detail::iecRound(v)); }
inline SINT REAL_TO_SINT(REAL v)  { return static_cast<SINT>(detail::iecRound(v)); }

inline INT  LREAL_TO_INT(LREAL v) { return static_cast<INT>(detail::iecRound(v)); }
inline DINT LREAL_TO_DINT(LREAL v){ return static_cast<DINT>(detail::iecRound(v)); }
inline LINT LREAL_TO_LINT(LREAL v){ return static_cast<LINT>(detail::iecRound(v)); }
inline SINT LREAL_TO_SINT(LREAL v){ return static_cast<SINT>(detail::iecRound(v)); }

/*
 * Floating point -> Integer (explicit truncation, non-IEC-default)
 * Use only when the ST source explicitly calls TRUNC()
 */

inline DINT TRUNC(REAL v)  { return static_cast<DINT>(v); }
inline LINT TRUNC(LREAL v) { return static_cast<LINT>(v); }

// Floating point <-> Floating point

inline LREAL REAL_TO_LREAL(REAL v)  { return static_cast<LREAL>(v); }
inline REAL  LREAL_TO_REAL(LREAL v) { return static_cast<REAL>(v); } // may lose precision

// Boolean <-> Integer

inline BOOL INT_TO_BOOL(INT v)   { return v != 0; }
inline INT  BOOL_TO_INT(BOOL v)  { return v ? 1 : 0; }
inline BOOL DINT_TO_BOOL(DINT v) { return v != 0; }
inline DINT BOOL_TO_DINT(BOOL v) { return v ? 1 : 0; }

// Bit strings <-> Integer (reinterpretation, same width, no value change)

inline WORD  INT_TO_WORD(INT v)   { return static_cast<WORD>(v); }
inline INT   WORD_TO_INT(WORD v)  { return static_cast<INT>(v); }
inline DWORD DINT_TO_DWORD(DINT v){ return static_cast<DWORD>(v); }
inline DINT  DWORD_TO_DINT(DWORD v){ return static_cast<DINT>(v); }
inline LWORD LINT_TO_LWORD(LINT v){ return static_cast<LWORD>(v); }
inline LINT  LWORD_TO_LINT(LWORD v){ return static_cast<LINT>(v); }

inline BYTE  SINT_TO_BYTE(SINT v) { return static_cast<BYTE>(v); }
inline SINT  BYTE_TO_SINT(BYTE v) { return static_cast<SINT>(v); }

/*
 * BCD conversions (Binary-Coded Decimal)
 * Common in industrial displays, rotary encoders, thumbwheel switches.
 * Each nibble (4 bits) encodes one decimal digit [0..9].
 */

/**
 * @brief Convert a BCD-encoded byte to its decimal value
 * @throws std::invalid_argument if any nibble is not a valid BCD digit (0-9)
 */
inline USINT BCD_TO_USINT(BYTE bcd)
{
    UInt8 lo = bcd & 0x0F;
    UInt8 hi = (bcd >> 4) & 0x0F;
    if (lo > 9 || hi > 9) {
        throw std::invalid_argument("BCD_TO_USINT: invalid BCD digit");
    }
    return static_cast<USINT>(hi * 10 + lo);
}

/**
 * @brief Convert a decimal value [0..99] to BCD-encoded byte
 * @throws std::out_of_range if value exceeds 2-digit BCD range
 */
inline BYTE USINT_TO_BCD(USINT value)
{
    if (value > 99) {
        throw std::out_of_range("USINT_TO_BCD: value exceeds 2-digit BCD range");
    }
    return static_cast<BYTE>(((value / 10) << 4) | (value % 10));
}

/**
 * @brief Convert a BCD-encoded word to its decimal value (4 digits)
 * @throws std::invalid_argument if any nibble is not a valid BCD digit (0-9)
 */
inline UINT BCD_TO_INT(WORD bcd)
{
    UInt16 result = 0;
    UInt16 multiplier = 1;
    for (int shift = 0; shift < 16; shift += 4) {
        UInt16 nibble = (bcd >> shift) & 0x0F;
        if (nibble > 9) {
            throw std::invalid_argument("BCD_TO_INT: invalid BCD digit");
        }
        result += static_cast<UInt16>(nibble * multiplier);
        multiplier *= 10;
    }
    return static_cast<UINT>(result);
}

/**
 * @brief Convert a decimal value [0..9999] to BCD-encoded word
 * @throws std::out_of_range if value exceeds 4-digit BCD range
 */
inline WORD INT_TO_BCD(UINT value)
{
    if (value > 9999) {
        throw std::out_of_range("INT_TO_BCD: value exceeds 4-digit BCD range");
    }
    UInt16 result = 0;
    UInt16 v = value;
    for (int shift = 0; shift < 16 && v > 0; shift += 4) {
        result |= static_cast<UInt16>((v % 10) << shift);
        v /= 10;
    }
    return static_cast<WORD>(result);
}

// String <-> Numeric conversions

inline STRING INT_TO_STRING(INT v)   { return std::to_string(v); }
inline STRING DINT_TO_STRING(DINT v) { return std::to_string(v); }
inline STRING LINT_TO_STRING(LINT v) { return std::to_string(v); }
inline STRING REAL_TO_STRING(REAL v) { return std::to_string(v); }
inline STRING LREAL_TO_STRING(LREAL v){ return std::to_string(v); }
inline STRING BOOL_TO_STRING(BOOL v) { return v ? "TRUE" : "FALSE"; }

/**
 * @brief STRING_TO_INT
 * @throws std::invalid_argument if the string does not contain a valid integer
 */
inline INT STRING_TO_INT(const STRING& s)
{
    return static_cast<INT>(std::stoi(s));
}

inline DINT STRING_TO_DINT(const STRING& s)
{
    return static_cast<DINT>(std::stol(s));
}

inline REAL STRING_TO_REAL(const STRING& s)
{
    return static_cast<REAL>(std::stof(s));
}

inline LREAL STRING_TO_LREAL(const STRING& s)
{
    return std::stod(s);
}

inline BOOL STRING_TO_BOOL(const STRING& s)
{
    return (s == "TRUE" || s == "true" || s == "1");
}

/*
 * STRING <-> WSTRING (width conversion)
 *
 * NOTE: this is a minimal, locale-independent conversion intended for
 * ASCII/Latin-1 industrial text (tag names, alarm messages). It does not
 * perform full Unicode-aware transcoding. Revisit if multi-byte UTF-8
 * support becomes a requirement for HMI text.
 */

/**
 * @brief Convert WSTRING to STRING by narrowing each character
 * @throws std::range_error if any character exceeds 0xFF (non Latin-1)
 */
inline STRING WSTRING_TO_STRING(const WSTRING& ws)
{
    STRING result;
    result.reserve(ws.size());
    for (wchar_t wc : ws) {
        if (static_cast<unsigned long>(wc) > 0xFF) {
            throw std::range_error("WSTRING_TO_STRING: character out of Latin-1 range");
        }
        result.push_back(static_cast<char>(wc));
    }
    return result;
}

/**
 * @brief Convert STRING to WSTRING by widening each character
 */
inline WSTRING STRING_TO_WSTRING(const STRING& s)
{
    WSTRING result;
    result.reserve(s.size());
    for (unsigned char c : s) {
        result.push_back(static_cast<wchar_t>(c));
    }
    return result;
}

// TIME conversions

inline TIME  DINT_TO_TIME(DINT v)  { return static_cast<TIME>(v); } // milliseconds
inline DINT  TIME_TO_DINT(TIME v)  { return static_cast<DINT>(v); }
inline STRING TIME_TO_STRING(TIME v) { return std::to_string(v) + "ms"; }

/*
 * DATE / TIME_OF_DAY / DATE_AND_TIME conversions
 *
 * Representation recap (see types.hpp):
 *   DATE            -> seconds since 1970-01-01 UTC, truncated to midnight
 *   TIME_OF_DAY(TOD)-> milliseconds since midnight
 *   DATE_AND_TIME(DT)-> seconds since 1970-01-01 UTC (full timestamp)
 *
 * All calendar decomposition uses gmtime (UTC), never local time.
 */

/**
 * @brief Extract the date-only part (midnight UTC) from a DATE_AND_TIME
 */
inline DATE DT_TO_DATE(DT dt)
{
    std::time_t t = static_cast<std::time_t>(dt);
    std::tm tmVal{};
    gmtime_r(&t, &tmVal);
    tmVal.tm_hour = 0;
    tmVal.tm_min  = 0;
    tmVal.tm_sec  = 0;
    return static_cast<DATE>(timegm(&tmVal));
}

/**
 * @brief Extract the time-of-day part (milliseconds since midnight) from a DATE_AND_TIME
 */
inline TOD DT_TO_TOD(DT dt)
{
    std::time_t t = static_cast<std::time_t>(dt);
    std::tm tmVal{};
    gmtime_r(&t, &tmVal);
    UInt64 msOfDay = (static_cast<UInt64>(tmVal.tm_hour) * 3600ULL
                    + static_cast<UInt64>(tmVal.tm_min)  * 60ULL
                    + static_cast<UInt64>(tmVal.tm_sec)) * 1000ULL;
    return static_cast<TOD>(msOfDay);
}

/**
 * @brief Combine a DATE (midnight) with a TIME_OF_DAY into a full DATE_AND_TIME
 */
inline DT DATE_TOD_TO_DT(DATE date, TOD tod)
{
    return static_cast<DT>(date) + static_cast<DT>(tod / 1000ULL);
}

/**
 * @brief Promote a DATE to DATE_AND_TIME at midnight (00:00:00)
 */
inline DT DATE_TO_DT(DATE date)
{
    return static_cast<DT>(date);
}

/**
 * @brief Convert TIME_OF_DAY to TIME (same unit: milliseconds)
 */
inline TIME TOD_TO_TIME(TOD tod)
{
    return static_cast<TIME>(tod);
}

/**
 * @brief Convert TIME to TIME_OF_DAY (same unit: milliseconds)
 * Value is not wrapped to a 24h range — caller responsibility if needed.
 */
inline TOD TIME_TO_TOD(TIME t)
{
    return static_cast<TOD>(t);
}

inline STRING DATE_TO_STRING(DATE date)
{
    std::time_t t = static_cast<std::time_t>(date);
    std::tm tmVal{};
    gmtime_r(&t, &tmVal);
    char buf[16];
    std::snprintf(buf, sizeof(buf), "%04d-%02d-%02d",
                  tmVal.tm_year + 1900, tmVal.tm_mon + 1, tmVal.tm_mday);
    return STRING(buf);
}

inline STRING TOD_TO_STRING(TOD tod)
{
    UInt64 totalMs = tod;
    UInt32 h = static_cast<UInt32>(totalMs / 3600000ULL);
    UInt32 m = static_cast<UInt32>((totalMs / 60000ULL) % 60ULL);
    UInt32 s = static_cast<UInt32>((totalMs / 1000ULL) % 60ULL);
    char buf[16];
    std::snprintf(buf, sizeof(buf), "%02u:%02u:%02u", h, m, s);
    return STRING(buf);
}

inline STRING DT_TO_STRING(DT dt)
{
    return DATE_TO_STRING(DT_TO_DATE(dt)) + "-" + TOD_TO_STRING(DT_TO_TOD(dt));
}

} // namespace undoCore