/**
* @file types.hpp
* @brief Support library for basic types
* @author Salvatore Bamundo
* @date June 2026
* SPDX-License-Identifier: GPL-3.0-or-later
* SPDX-FileCopyrightText: Copyright (c) 2026 undoRT
*
* This header provides the runtime type definitions and utilities
* for code generated by the st2cpp compiler from IEC 61131-3 Structured Text.
*/

#pragma once

#include <cstdint>
#include <cstring>
#include <string>
#include <array>
#include <algorithm>
#include <initializer_list>
#include <stdexcept>

namespace undoCore {

// ============================================================================
// IEC 61131-3 Elementary Types mapped to C++
// ============================================================================

// Boolean type
using Bool = bool;

// Integer types (signed)
using Int8 = int8_t;   // SINT
using Int16 = int16_t; // INT
using Int32 = int32_t; // DINT
using Int64 = int64_t; // LINT

// Integer types (unsigned)
using UInt8 = uint8_t;   // USINT
using UInt16 = uint16_t; // UINT
using UInt32 = uint32_t; // UDINT
using UInt64 = uint64_t; // ULINT

// Floating point types
using Float = float;   // REAL
using Double = double; // LREAL

// Bit strings
using Byte = uint8_t;   // BYTE
using Word = uint16_t;  // WORD
using Dword = uint32_t; // DWORD
using Lword = uint64_t; // LWORD

// Character strings
using String = std::string;   // STRING
using Wstring = std::wstring; // WSTRING

// Date and time types (represented as seconds or milliseconds)
using Time = UInt32; // TIME (milliseconds)
using Date = UInt32; // DATE (seconds since 1970-01-01)
using Tod = UInt64;  // TIME_OF_DAY (milliseconds since midnight)
using Dt = UInt64;   // DATE_AND_TIME (seconds since 1970-01-01)

// Void type for functions with no return value
using Void = void;

// ============================================================================
// VAR_IN_OUT Template Wrapper
// ============================================================================

/**
* @brief Wrapper for VAR_IN_OUT parameters
* @tparam T Type of the referenced variable
*
* In IEC 61131-3, VAR_IN_OUT parameters are passed by reference.
* This template provides a clean wrapper for such parameters.
*/
template<typename T>
struct VarInOut
{
   VarInOut(T& ref) : ptr(&ref) {}
   VarInOut() : ptr(nullptr) {}

   VarInOut& operator=(T& ref)
   {
      ptr = &ref;
      return *this;
   }

   operator T&() const { return *ptr; }
   T& operator*() const
   {
      static_assert(ptr != nullptr && "VarInOut: null dereference");
      return *ptr;
   }
   T* operator->() const { return ptr; }

   T* ptr;
};

// Alias for backward compatibility
template<typename T>
using VAR_INOUT = VarInOut<T>;

// ============================================================================
// STArray Template for IEC 61131-3 Arrays
// ============================================================================

/**
 * @brief Array template compatible with IEC 61131-3 array semantics
 * @tparam T Type of array elements (can be another STArray for multi-dim)
 * @tparam Low Lower bound index (inclusive)
 * @tparam High Upper bound index (inclusive)
 *
 * Supports multidimensional arrays through nesting:
 *   STArray<STArray<Int, 0, 4>, 1, 3>  // 3x5 array (indices [1..3][0..4])
 *
 * Example usage:
 *   STArray<Int, 1, 10> arr1d;                   // 1D array
 *   STArray<STArray<Int, 0, 4>, 1, 3> arr2d;     // 2D array
 *   arr2d[2][3] = 42;                            // Access element
 */
template<typename T, int Low, int High>
class STArray
{
   static_assert(High >= Low, "High bound must be greater than or equal to Low bound");

   static constexpr size_t SIZE = (High - Low + 1);
   std::array<T, SIZE> data;

public:
   // Type aliases
   using value_type = T;
   using reference = T&;
   using const_reference = const T&;
   using iterator = typename std::array<T, SIZE>::iterator;
   using const_iterator = typename std::array<T, SIZE>::const_iterator;

   // Constructors
   STArray() = default;

   // Initializer list constructor (for 1D arrays)
   STArray(std::initializer_list<T> init)
   {
      size_t i = 0;
      for (const auto& val : init) {
         if (i < SIZE) {
            data[i++] = val;
         }
      }
   }

   // Element access with bounds checking
   reference operator[](int index)
   {
      if (index < Low || index > High) {
         throw std::out_of_range("STArray index out of bounds");
      }
      return data[index - Low];
   }

   const_reference operator[](int index) const
   {
      if (index < Low || index > High) {
         throw std::out_of_range("STArray index out of bounds");
      }
      return data[index - Low];
   }

   // Bounds information
   static constexpr int low() { return Low; }
   static constexpr int high() { return High; }
   static constexpr size_t size() { return SIZE; }

   // Raw data access
   T* data_ptr() { return data.data(); }
   const T* data_ptr() const { return data.data(); }

   // Iterators
   iterator begin() { return data.begin(); }
   iterator end() { return data.end(); }
   const_iterator begin() const { return data.begin(); }
   const_iterator end() const { return data.end(); }

   // Fill with a value
   void fill(const T& value) { std::fill(data.begin(), data.end(), value); }
};

// ============================================================================
// Time Literal Helper
// ============================================================================

/**
* @brief Convert TIME literal string to milliseconds
* @param literal TIME literal in IEC format (e.g., "T#10s", "T#100ms")
* @return Time value in milliseconds
*
* Supported suffixes:
* - ms: milliseconds
* - s: seconds
* - m: minutes
* - h: hours
* - d: days
*/
inline Time TIME_LITERAL(const char* literal)
{
   std::string str(literal);
   size_t i = 0;
   while (i < str.size() && (std::isdigit(str[i]) || str[i] == '.')) {
      ++i;
   }

   double num = std::stod(str.substr(0, i));
   std::string suffix = str.substr(i);

   if (suffix == "ms") {
      return static_cast<Time>(num);
   }
   if (suffix == "s") {
      return static_cast<Time>(num * 1000);
   }
   if (suffix == "m") {
      return static_cast<Time>(num * 60000);
   }
   if (suffix == "h") {
      return static_cast<Time>(num * 3600000);
   }
   if (suffix == "d") {
      return static_cast<Time>(num * 86400000);
   }
   return 0;
}

// ============================================================================
// Type Aliases for Common IEC Types (for generated code compatibility)
// ============================================================================

// These aliases match the names used by the code generator
using BOOL = Bool;
using SINT = Int8;
using INT = Int16;
using DINT = Int32;
using LINT = Int64;
using USINT = UInt8;
using UINT = UInt16;
using UDINT = UInt32;
using ULINT = UInt64;
using REAL = Float;
using LREAL = Double;
using BYTE = Byte;
using WORD = Word;
using DWORD = Dword;
using LWORD = Lword;
using STRING = String;
using WSTRING = Wstring;
using TIME = Time;
// TODO: consider UInt64 for post-2106 safety
using DATE = Date;
using TOD = Tod;
using DT = Dt;

} // namespace undoCore