/**
 * @file math.hpp
 * @brief IEC 61131-3 standard mathematical functions
 * @author Salvatore Bamundo
 * @date July 2026
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: Copyright (c) 2026 undoRT
 *
 * This header provides the runtime implementation of IEC 61131-3
 * standard mathematical functions used by code generated by the
 * st2cpp compiler.
 *
 * Functions included:
 *   - Arithmetic: ABS, SQRT, LN, LOG, EXP, SIN, COS, TAN, ASIN, ACOS, ATAN
 *   - Power: EXPT
 *   - Truncation: FLOOR, CEIL, TRUNC, ROUND
 *   - Bit operations: SHL, SHR, ROL, ROR
 *   - Selection: MIN, MAX, MUX, LIMIT
 *   - Comparison: EQ, NE, LT, LE, GT, GE (via operators)
 *   - Type checking: IS_NAN, IS_INFINITE
 *
 * All functions follow IEC 61131-3 semantics where applicable.
 * For bit operations, the shift count is interpreted modulo the bit width.
 */

#pragma once

#include <cmath>
#include <cstdint>
#include <algorithm>
#include <type_traits>

#include "types.hpp"

namespace undoCore {

// ============================================================================
// Helper traits and utilities
// ============================================================================

namespace detail {

/**
 * @brief Check if a type is an integer type (signed or unsigned)
 */
template<typename T>
using is_integer = std::is_integral<T>;

/**
 * @brief Check if a type is a floating point type
 */
template<typename T>
using is_float = std::is_floating_point<T>;

/**
 * @brief Check if a type is a bit string type (BYTE, WORD, DWORD, LWORD)
 */
template<typename T>
struct is_bitstring : std::false_type
{};

template<>
struct is_bitstring<BYTE> : std::true_type
{};

template<>
struct is_bitstring<WORD> : std::true_type
{};

template<>
struct is_bitstring<DWORD> : std::true_type
{};

template<>
struct is_bitstring<LWORD> : std::true_type
{};

/**
 * @brief Get the bit width of a type
 */
template<typename T>
struct bit_width;

template<>
struct bit_width<BYTE> : std::integral_constant<int, 8>
{};
template<>
struct bit_width<WORD> : std::integral_constant<int, 16>
{};
template<>
struct bit_width<DWORD> : std::integral_constant<int, 32>
{};
template<>
struct bit_width<LWORD> : std::integral_constant<int, 64>
{};

/**
 * @brief Get the bit mask for a type (all bits set)
 */
template<typename T>
inline T allBits()
{
   return static_cast<T>(~static_cast<T>(0));
}

/**
 * @brief Get the sign bit mask for a signed integer type
 */
template<typename T>
inline T signBit()
{
   return static_cast<T>(static_cast<typename std::make_unsigned<T>::type>(1) << (sizeof(T) * 8 - 1));
}

} // namespace detail

// ============================================================================
// Absolute value
// ============================================================================

/**
 * @brief Absolute value
 * 
 * IEC 61131-3: ABS(x)
 * Returns the absolute value of x.
 * For signed integers, ABS(MIN) is undefined (wraps to MIN).
 */
template<typename T>
inline T ABS(T x)
{
   if constexpr (detail::is_float<T>::value) {
      return std::abs(x);
   } else if constexpr (std::is_unsigned<T>::value) {
      return x;
   } else {
      return x < 0 ? -x : x;
   }
}

// Overload for LREAL (Double)
inline LREAL ABS(LREAL x)
{
   return std::abs(x);
}

// ============================================================================
// Square root
// ============================================================================

/**
 * @brief Square root
 * 
 * IEC 61131-3: SQRT(x)
 * Returns the square root of x. x must be non-negative.
 */
template<typename T>
inline T SQRT(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "SQRT is only defined for floating point types");
   return std::sqrt(x);
}

inline LREAL SQRT(LREAL x)
{
   return std::sqrt(x);
}

// ============================================================================
// Natural logarithm
// ============================================================================

/**
 * @brief Natural logarithm (base e)
 * 
 * IEC 61131-3: LN(x)
 * Returns the natural logarithm of x. x must be positive.
 */
template<typename T>
inline T LN(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "LN is only defined for floating point types");
   return std::log(x);
}

inline LREAL LN(LREAL x)
{
   return std::log(x);
}

// ============================================================================
// Common logarithm (base 10)
// ============================================================================

/**
 * @brief Common logarithm (base 10)
 * 
 * IEC 61131-3: LOG(x)
 * Returns the base-10 logarithm of x. x must be positive.
 */
template<typename T>
inline T LOG(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "LOG is only defined for floating point types");
   return std::log10(x);
}

inline LREAL LOG(LREAL x)
{
   return std::log10(x);
}

// ============================================================================
// Exponential (e^x)
// ============================================================================

/**
 * @brief Exponential function (e^x)
 * 
 * IEC 61131-3: EXP(x)
 * Returns e raised to the power of x.
 */
template<typename T>
inline T EXP(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "EXP is only defined for floating point types");
   return std::exp(x);
}

inline LREAL EXP(LREAL x)
{
   return std::exp(x);
}

// ============================================================================
// Trigonometric functions
// ============================================================================

/**
 * @brief Sine
 * 
 * IEC 61131-3: SIN(x)
 * Returns the sine of x (x in radians).
 */
template<typename T>
inline T SIN(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "SIN is only defined for floating point types");
   return std::sin(x);
}

inline LREAL SIN(LREAL x)
{
   return std::sin(x);
}

/**
 * @brief Cosine
 * 
 * IEC 61131-3: COS(x)
 * Returns the cosine of x (x in radians).
 */
template<typename T>
inline T COS(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "COS is only defined for floating point types");
   return std::cos(x);
}

inline LREAL COS(LREAL x)
{
   return std::cos(x);
}

/**
 * @brief Tangent
 * 
 * IEC 61131-3: TAN(x)
 * Returns the tangent of x (x in radians).
 */
template<typename T>
inline T TAN(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "TAN is only defined for floating point types");
   return std::tan(x);
}

inline LREAL TAN(LREAL x)
{
   return std::tan(x);
}

// ============================================================================
// Inverse trigonometric functions
// ============================================================================

/**
 * @brief Arc sine
 * 
 * IEC 61131-3: ASIN(x)
 * Returns the arc sine of x (in radians). x must be in [-1, 1].
 */
template<typename T>
inline T ASIN(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "ASIN is only defined for floating point types");
   return std::asin(x);
}

inline LREAL ASIN(LREAL x)
{
   return std::asin(x);
}

/**
 * @brief Arc cosine
 * 
 * IEC 61131-3: ACOS(x)
 * Returns the arc cosine of x (in radians). x must be in [-1, 1].
 */
template<typename T>
inline T ACOS(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "ACOS is only defined for floating point types");
   return std::acos(x);
}

inline LREAL ACOS(LREAL x)
{
   return std::acos(x);
}

/**
 * @brief Arc tangent
 * 
 * IEC 61131-3: ATAN(x)
 * Returns the arc tangent of x (in radians).
 */
template<typename T>
inline T ATAN(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "ATAN is only defined for floating point types");
   return std::atan(x);
}

inline LREAL ATAN(LREAL x)
{
   return std::atan(x);
}

/**
 * @brief Arc tangent with two arguments
 * 
 * IEC 61131-3: ATAN2(y, x)
 * Returns the arc tangent of y/x (in radians), using the signs of both
 * arguments to determine the quadrant.
 */
template<typename T>
inline T ATAN2(T y, T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "ATAN2 is only defined for floating point types");
   return std::atan2(y, x);
}

inline LREAL ATAN2(LREAL y, LREAL x)
{
   return std::atan2(y, x);
}

// ============================================================================
// Power function
// ============================================================================

/**
 * @brief Power function (x^y)
 * 
 * IEC 61131-3: EXPT(x, y)
 * Returns x raised to the power of y.
 */
template<typename T>
inline T EXPT(T x, T y)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "EXPT is only defined for floating point types");
   return std::pow(x, y);
}

inline LREAL EXPT(LREAL x, LREAL y)
{
   return std::pow(x, y);
}

// ============================================================================
// Floor, Ceil, Trunc, Round
// ============================================================================

/**
 * @brief Floor (largest integer <= x)
 * 
 * IEC 61131-3: FLOOR(x)
 * Returns the largest integer less than or equal to x.
 */
template<typename T>
inline T FLOOR(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "FLOOR is only defined for floating point types");
   return std::floor(x);
}

inline LREAL FLOOR(LREAL x)
{
   return std::floor(x);
}

/**
 * @brief Ceiling (smallest integer >= x)
 * 
 * IEC 61131-3: CEIL(x)
 * Returns the smallest integer greater than or equal to x.
 */
template<typename T>
inline T CEIL(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "CEIL is only defined for floating point types");
   return std::ceil(x);
}

inline LREAL CEIL(LREAL x)
{
   return std::ceil(x);
}

/**
 * @brief Truncate (toward zero)
 * 
 * IEC 61131-3: TRUNC(x)
 * Returns the integer part of x, truncating toward zero.
 */
template<typename T>
inline T TRUNC(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "TRUNC is only defined for floating point types");
   return std::trunc(x);
}

inline LREAL TRUNC(LREAL x)
{
   return std::trunc(x);
}

/**
 * @brief Round (nearest integer, ties away from zero)
 * 
 * IEC 61131-3: ROUND(x)
 * Returns the nearest integer to x, with ties rounded away from zero.
 */
template<typename T>
inline T ROUND(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "ROUND is only defined for floating point types");
   return std::round(x);
}

inline LREAL ROUND(LREAL x)
{
   return std::round(x);
}

// ============================================================================
// Bit shift operations
// ============================================================================

/**
 * @brief Shift left
 * 
 * IEC 61131-3: SHL(x, n)
 * Shifts x left by n bits. The result is modulo 2^bit_width.
 * For bit strings, the shift count is interpreted modulo the bit width.
 */
template<typename T>
inline T SHL(T x, int n)
{
   static_assert(detail::is_bitstring<T>::value, "SHL is only defined for bit string types (BYTE, WORD, DWORD, LWORD)");
   constexpr int width = detail::bit_width<T>::value;
   n = n % width;
   return static_cast<T>((static_cast<typename std::make_unsigned<T>::type>(x) << n) & detail::allBits<T>());
}

// Overload for UInt types (unsigned integers)
template<typename T>
inline T SHL_INT(T x, int n)
{
   static_assert(std::is_unsigned<T>::value, "SHL_INT is only defined for unsigned integer types");
   constexpr int width = sizeof(T) * 8;
   n = n % width;
   if (n >= width) {
      return 0;
   }
   return static_cast<T>(x << n);
}

// ============================================================================
// Shift right (logical)
// ============================================================================

/**
 * @brief Shift right (logical)
 * 
 * IEC 61131-3: SHR(x, n)
 * Shifts x right by n bits (logical shift, zero-fill).
 * For bit strings, the shift count is interpreted modulo the bit width.
 */
template<typename T>
inline T SHR(T x, int n)
{
   static_assert(detail::is_bitstring<T>::value, "SHR is only defined for bit string types (BYTE, WORD, DWORD, LWORD)");
   constexpr int width = detail::bit_width<T>::value;
   n = n % width;
   return static_cast<T>((static_cast<typename std::make_unsigned<T>::type>(x) >> n) & detail::allBits<T>());
}

// Overload for UInt types (unsigned integers)
template<typename T>
inline T SHR_INT(T x, int n)
{
   static_assert(std::is_unsigned<T>::value, "SHR_INT is only defined for unsigned integer types");
   constexpr int width = sizeof(T) * 8;
   n = n % width;
   if (n >= width) {
      return 0;
   }
   return static_cast<T>(x >> n);
}

// ============================================================================
// Rotate left
// ============================================================================

/**
 * @brief Rotate left
 * 
 * IEC 61131-3: ROL(x, n)
 * Rotates x left by n bits. Bits shifted out on the left are
 * shifted in on the right.
 * For bit strings, the shift count is interpreted modulo the bit width.
 */
template<typename T>
inline T ROL(T x, int n)
{
   static_assert(detail::is_bitstring<T>::value, "ROL is only defined for bit string types (BYTE, WORD, DWORD, LWORD)");
   constexpr int width = detail::bit_width<T>::value;
   n = n % width;
   using U = typename std::make_unsigned<T>::type;
   U ux = static_cast<U>(x);
   U result = (ux << n) | (ux >> (width - n));
   return static_cast<T>(result & detail::allBits<T>());
}

// Overload for UInt types (unsigned integers)
template<typename T>
inline T ROL_INT(T x, int n)
{
   static_assert(std::is_unsigned<T>::value, "ROL_INT is only defined for unsigned integer types");
   constexpr int width = sizeof(T) * 8;
   n = n % width;
   if (n == 0) {
      return x;
   }
   return static_cast<T>((x << n) | (x >> (width - n)));
}

// ============================================================================
// Rotate right
// ============================================================================

/**
 * @brief Rotate right
 * 
 * IEC 61131-3: ROR(x, n)
 * Rotates x right by n bits. Bits shifted out on the right are
 * shifted in on the left.
 * For bit strings, the shift count is interpreted modulo the bit width.
 */
template<typename T>
inline T ROR(T x, int n)
{
   static_assert(detail::is_bitstring<T>::value, "ROR is only defined for bit string types (BYTE, WORD, DWORD, LWORD)");
   constexpr int width = detail::bit_width<T>::value;
   n = n % width;
   using U = typename std::make_unsigned<T>::type;
   U ux = static_cast<U>(x);
   U result = (ux >> n) | (ux << (width - n));
   return static_cast<T>(result & detail::allBits<T>());
}

// Overload for UInt types (unsigned integers)
template<typename T>
inline T ROR_INT(T x, int n)
{
   static_assert(std::is_unsigned<T>::value, "ROR_INT is only defined for unsigned integer types");
   constexpr int width = sizeof(T) * 8;
   n = n % width;
   if (n == 0) {
      return x;
   }
   return static_cast<T>((x >> n) | (x << (width - n)));
}

// ============================================================================
// Selection functions
// ============================================================================

/**
 * @brief Minimum of two values
 * 
 * IEC 61131-3: MIN(x, y)
 * Returns the smaller of x and y.
 */
template<typename T>
inline T MIN(T x, T y)
{
   return x < y ? x : y;
}

/**
 * @brief Minimum of three or more values (variadic)
 * 
 * IEC 61131-3: MIN(x, y, z, ...)
 * Returns the smallest of all arguments.
 */
template<typename T, typename... Args>
inline T MIN(T first, Args... args)
{
   T rest = MIN(args...);
   return first < rest ? first : rest;
}

/**
 * @brief Maximum of two values
 * 
 * IEC 61131-3: MAX(x, y)
 * Returns the larger of x and y.
 */
template<typename T>
inline T MAX(T x, T y)
{
   return x > y ? x : y;
}

/**
 * @brief Maximum of three or more values (variadic)
 * 
 * IEC 61131-3: MAX(x, y, z, ...)
 * Returns the largest of all arguments.
 */
template<typename T, typename... Args>
inline T MAX(T first, Args... args)
{
   T rest = MAX(args...);
   return first > rest ? first : rest;
}

/**
 * @brief Multiplexer
 * 
 * IEC 61131-3: MUX(k, x0, x1, ..., xn)
 * Returns the k-th input (0-indexed). k must be in [0, n].
 * 
 * Note: This is implemented as a variadic template. The first argument
 * is the index, followed by the values to select from.
 */
template<typename T, typename... Args>
inline T MUX(int k, T first, Args... args)
{
   if (k == 0) {
      return first;
   }
   return MUX(k - 1, args...);
}

// Base case for MUX (single value)
template<typename T>
inline T MUX(int k, T value)
{
   // If k is not 0, this is an out-of-range access
   // IEC behavior: undefined, we return the last value
   return value;
}

/**
 * @brief Limit
 * 
 * IEC 61131-3: LIMIT(min, x, max)
 * Returns:
 *   - min if x < min
 *   - max if x > max
 *   - x otherwise
 */
template<typename T>
inline T LIMIT(T min, T x, T max)
{
   if (x < min) {
      return min;
   }
   if (x > max) {
      return max;
   }
   return x;
}

// ============================================================================
// Type checking functions
// ============================================================================

/**
 * @brief Check if a value is NaN (Not a Number)
 * 
 * IEC 61131-3: IS_NAN(x)
 * Returns true if x is NaN, false otherwise.
 */
template<typename T>
inline BOOL IS_NAN(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "IS_NAN is only defined for floating point types");
   return std::isnan(x) ? true : false;
}

inline BOOL IS_NAN(LREAL x)
{
   return std::isnan(x) ? true : false;
}

/**
 * @brief Check if a value is infinite
 * 
 * IEC 61131-3: IS_INFINITE(x)
 * Returns true if x is infinite, false otherwise.
 */
template<typename T>
inline BOOL IS_INFINITE(T x)
{
   static_assert(detail::is_float<T>::value || std::is_same<T, LREAL>::value, "IS_INFINITE is only defined for floating point types");
   return std::isinf(x) ? true : false;
}

inline BOOL IS_INFINITE(LREAL x)
{
   return std::isinf(x) ? true : false;
}

// ============================================================================
// Additional bit operations
// ============================================================================

/**
 * @brief Bitwise NOT (complement)
 * 
 * Returns the bitwise complement of x (all bits inverted).
 */
template<typename T>
inline T NOT(T x)
{
   static_assert(detail::is_bitstring<T>::value || std::is_integral<T>::value, "NOT is only defined for bit string and integral types");
   return static_cast<T>(~static_cast<typename std::make_unsigned<T>::type>(x) & detail::allBits<T>());
}

/**
 * @brief Bitwise AND
 * 
 * Returns the bitwise AND of x and y.
 */
template<typename T>
inline T AND(T x, T y)
{
   static_assert(detail::is_bitstring<T>::value || std::is_integral<T>::value, "AND is only defined for bit string and integral types");
   return static_cast<T>(static_cast<typename std::make_unsigned<T>::type>(x) & static_cast<typename std::make_unsigned<T>::type>(y));
}

/**
 * @brief Bitwise OR
 * 
 * Returns the bitwise OR of x and y.
 */
template<typename T>
inline T OR(T x, T y)
{
   static_assert(detail::is_bitstring<T>::value || std::is_integral<T>::value, "OR is only defined for bit string and integral types");
   return static_cast<T>(static_cast<typename std::make_unsigned<T>::type>(x) | static_cast<typename std::make_unsigned<T>::type>(y));
}

/**
 * @brief Bitwise XOR
 * 
 * Returns the bitwise XOR of x and y.
 */
template<typename T>
inline T XOR(T x, T y)
{
   static_assert(detail::is_bitstring<T>::value || std::is_integral<T>::value, "XOR is only defined for bit string and integral types");
   return static_cast<T>(static_cast<typename std::make_unsigned<T>::type>(x) ^ static_cast<typename std::make_unsigned<T>::type>(y));
}

// ============================================================================
// Integer division and modulo (with proper handling of negative values)
// ============================================================================

/**
 * @brief Integer division (truncate toward zero)
 * 
 * IEC 61131-3: DIV(x, y)
 * Returns the quotient of x divided by y, truncated toward zero.
 */
template<typename T>
inline T DIV(T x, T y)
{
   static_assert(std::is_integral<T>::value, "DIV is only defined for integral types");
   if constexpr (std::is_signed<T>::value) {
      return static_cast<T>(std::trunc(static_cast<LREAL>(x) / static_cast<LREAL>(y)));
   } else {
      return static_cast<T>(x / y);
   }
}

/**
 * @brief Integer modulo (remainder, same sign as dividend)
 * 
 * IEC 61131-3: MOD(x, y)
 * Returns the remainder of x divided by y.
 * The result has the same sign as x (dividend).
 */
template<typename T>
inline T MOD(T x, T y)
{
   static_assert(std::is_integral<T>::value, "MOD is only defined for integral types");
   if constexpr (std::is_signed<T>::value) {
      // For signed integers, result has same sign as x
      T quotient = static_cast<T>(std::trunc(static_cast<LREAL>(x) / static_cast<LREAL>(y)));
      return static_cast<T>(x - quotient * y);
   } else {
      return static_cast<T>(x % y);
   }
}

// ============================================================================
// Aliases for commonly used functions
// ============================================================================

// Short aliases for bit operations (for convenience in generated code)
using SHL = SHL;
using SHR = SHR;
using ROL = ROL;
using ROR = ROR;

} // namespace undoCore